name: Labss

on:
  push:
    branches: ["master","main"]
    
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/chechkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install numpy
        pip install pytest
      
    - name: Run test
      run: python -m pytest test.py
