name: test

on:
  push:
    branches: ["test"]
    
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pytest
        pip install fastapi
        pip install pydantic
        pip install requests
        pip install uvicorn[standard]
    - name: Run Docker
      run:  |
        docker build -t build -f lab6 .
        docker run -p 8000:8000 build
      
    - name: Run test
      run: python -m pytest app/tests.py
      
    - name: Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ sercets.PASSWORD }}
    - name: DockerBuild
      uses: docker/setup-build-action@v2
    - name: dockerPush
      uses: docker/build-push-action@v4
      with:
        context: _
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.USERNAME }}/stuffbox:latest
